server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # This tells Nginx: "If you can't find the file, just send them to index.html"
        try_files $uri $uri/ /index.html;
    }
}