// foodCalories.js
// All values are approximate per 100g
const foodCalories = {
  // Fruits
  "apple": { "calories": 52, "protein": 0.3 },
  "banana": { "calories": 89, "protein": 1.1 },
  "orange": { "calories": 47, "protein": 0.9 },
  "grapes": { "calories": 69, "protein": 0.7 },
  "mango": { "calories": 60, "protein": 0.8 },
  "pineapple": { "calories": 50, "protein": 0.5 },
  "strawberry": { "calories": 32, "protein": 0.7 },
  "blueberry": { "calories": 57, "protein": 0.7 },
  "watermelon": { "calories": 30, "protein": 0.6 },
  "papaya": { "calories": 43, "protein": 0.5 },
  "avocado": { "calories": 160, "protein": 2 },
  "pear": { "calories": 57, "protein": 0.4 },
  "peach": { "calories": 39, "protein": 0.9 },
  "cherry": { "calories": 50, "protein": 1 },
  "pomegranate": { "calories": 83, "protein": 1.7 },
  "kiwi": { "calories": 41, "protein": 1.1 },
  "guava": { "calories": 68, "protein": 2.6 },
  "lemon": { "calories": 29, "protein": 1.1 },

  // Vegetables
  "tomato": { "calories": 18, "protein": 0.9 },
  "cucumber": { "calories": 16, "protein": 0.7 },
  "carrot": { "calories": 41, "protein": 0.9 },
  "broccoli": { "calories": 34, "protein": 2.8 },
  "cauliflower": { "calories": 25, "protein": 1.9 },
  "spinach": { "calories": 23, "protein": 2.9 },
  "potato": { "calories": 77, "protein": 2 },
  "sweet potato": { "calories": 86, "protein": 1.6 },
  "corn": { "calories": 96, "protein": 3.4 },
  "peas": { "calories": 81, "protein": 5.4 },
  "onion": { "calories": 40, "protein": 1.1 },
  "garlic": { "calories": 149, "protein": 6.4 },
  "eggplant": { "calories": 25, "protein": 1 },
  "pumpkin": { "calories": 26, "protein": 1 },
  "beetroot": { "calories": 43, "protein": 1.6 },
  "lettuce": { "calories": 15, "protein": 1.4 },
  "cabbage": { "calories": 25, "protein": 1.3 },
  "okra": { "calories": 33, "protein": 1.9 },
  "mushroom": { "calories": 22, "protein": 3.1 },
  
  // Proteins (Meat, Dairy, Eggs)
  "chicken": {"calories": 165, "protein": 31 },
  "chicken breast (cooked)": { "calories": 165, "protein": 31 },
  "chicken thigh (cooked)": { "calories": 209, "protein": 26 },
  "chicken leg (cooked)": { "calories": 177, "protein": 28 },
  "chicken wings (cooked)": { "calories": 290, "protein": 30 },
  "chicken (roast, whole)": { "calories": 185, "protein": 29 },
  "egg (boiled)": { "calories": 155, "protein": 13 },
  "egg (fried)": { "calories": 196, "protein": 14 },
  "egg white": { "calories": 52, "protein": 11 },
  "fish (salmon, cooked)": { "calories": 206, "protein": 22 },
  "fish (tuna, canned)": { "calories": 116, "protein": 26 },
  "fish (cod, cooked)": { "calories": 105, "protein": 23 },
  "beef (ground, 80/20, cooked)": { "calories": 254, "protein": 26 },
  "beef (steak, sirloin, cooked)": { "calories": 183, "protein": 28 },
  "pork (loin, cooked)": { "calories": 231, "protein": 27 },
  "bacon (cooked)": { "calories": 541, "protein": 37 },
  "lamb (chop, cooked)": { "calories": 283, "protein": 25 },
  "shrimp (cooked)": { "calories": 99, "protein": 24 },
  "crab (cooked)": { "calories": 97, "protein": 20 },
  "tofu": { "calories": 76, "protein": 8 },
  "paneer": { "calories": 296, "protein": 18 },
  "milk (whole)": { "calories": 60, "protein": 3.3 },
  "milk (skimmed)": { "calories": 34, "protein": 3.4 },
  "yogurt (plain)": { "calories": 59, "protein": 10 },
  "greek yogurt (plain)": { "calories": 97, "protein": 9 },
  "cheese (cheddar)": { "calories": 404, "protein": 23 },
  "butter": { "calories": 717, "protein": 0.9 },
  "ghee": { "calories": 900, "protein": 0 },

  // Carbs & Grains
  "bread (white)": { "calories": 265, "protein": 9 },
  "bread (brown)": { "calories": 252, "protein": 11 },
  "rice (white, cooked)": { "calories": 130, "protein": 2.7 },
  "rice (brown, cooked)": { "calories": 111, "protein": 2.6 },
  "pasta (cooked)": { "calories": 131, "protein": 5 },
  "noodles (cooked)": { "calories": 138, "protein": 4.5 },
  "oats (uncooked)": { "calories": 389, "protein": 16.9 },
  "cornflakes": { "calories": 357, "protein": 7.5 },

  // Prepared Foods & Legumes
  "pizza (pepperoni)": { "calories": 298, "protein": 12 },
  "burger": { "calories": 295, "protein": 17 },
  "sandwich (ham & cheese)": { "calories": 280, "protein": 14 },
  "idli": { "calories": 130, "protein": 4 },
  "dosa (plain)": { "calories": 190, "protein": 4 },
  "chapati": { "calories": 297, "protein": 11 },
  "paratha": { "calories": 310, "protein": 7 },
  "poha": { "calories": 130, "protein": 2.5 },
  "upma": { "calories": 150, "protein": 4 },
  "samosa": { "calories": 262, "protein": 4.5 },
  "vada (medu)": { "calories": 330, "protein": 12 },
  "biryani (chicken)": { "calories": 180, "protein": 9 },
  "fried rice (chicken)": { "calories": 174, "protein": 7 },
  "lentils (dal, cooked)": { "calories": 116, "protein": 9 },
  "kidney beans (rajma, cooked)": { "calories": 127, "protein": 8.7 },
  "chickpeas (chole, cooked)": { "calories": 164, "protein": 9 },
  "paneer curry": { "calories": 160, "protein": 7 },
  "chicken curry": { "calories": 145, "protein": 15 },
  "mutton curry": { "calories": 170, "protein": 12 },
  "egg curry": { "calories": 150, "protein": 8 },
  "veg salad": { "calories": 70, "protein": 2 },
  "fruit salad": { "calories": 90, "protein": 1 },
  
  // Nuts, Sweets & Drinks
  "almonds": { "calories": 579, "protein": 21 },
  "cashew": { "calories": 553, "protein": 18 },
  "walnut": { "calories": 654, "protein": 15 },
  "peanuts": { "calories": 567, "protein": 26 },
  "dates": { "calories": 282, "protein": 2.5 },
  "honey": { "calories": 304, "protein": 0.3 },
  "sugar": { "calories": 387, "protein": 0 },
  "chocolate (dark)": { "calories": 546, "protein": 7.8 },
  "ice cream (vanilla)": { "calories": 207, "protein": 3.5 },
  "coffee (black)": { "calories": 2, "protein": 0.1 },
  "tea (without sugar)": { "calories": 1, "protein": 0.1 },
  "tea (with milk)": { "calories": 30, "protein": 1 },
  "coke": { "calories": 41, "protein": 0 },
  "juice (orange)": { "calories": 45, "protein": 0.7 },
  "juice (apple)": { "calories": 46, "protein": 0.1 }
};

export default foodCalories;