const PREDEFINED_EXERCISES = [
  { id: "ex1", name: "Barbell Bench Press" },
  { id: "ex2", name: "Dumbbell Bench Press" },
  { id: "ex3", name: "Incline Barbell Press" },
  { id: "ex4", name: "Incline Dumbbell Press" },
  { id: "ex5", name: "Push-up" },
  { id: "ex6", name: "Dip" },
  { id: "ex7", name: "Overhead Press (Barbell)" },
  { id: "ex8", name: "Dumbbell Shoulder Press" },
  { id: "ex9", name: "Lateral Raise" },
  { id: "ex10", name: "Tricep Pushdown" },
  { id: "ex11", name: "Skullcrusher" },
  { id: "ex12", name: "Squat (Barbell)" },
  { id: "ex13", name: "Leg Press" },
  { id: "ex14", name: "Lunge" },
  { id: "ex15", name: "Leg Extension" },
  { id: "ex16", name: "Leg Curl" },
  { id: "ex17", name: "Deadlift (Conventional)" },
  { id: "ex18", name: "Romanian Deadlift" },
  { id: "ex19", name: "Pull-up" },
  { id: "ex20", name: "Chin-up" },
  { id: "ex21", name: "Lat Pulldown" },
  { id: "ex22", name: "Bent Over Row (Barbell)" },
  { id: "ex23", name: "Dumbbell Row" },
  { id: "ex24", name: "Seated Cable Row" },
  { id: "ex25", name: "Cable Fly(Dumbbell)" },
  { id: "ex26", name: "Bicep Curl (Barbell)" },
  { id: "ex27", name: "Hammer Curl" },
  { id: "ex28", name: "Plank" },
  { id: "ex29", name: "Crunch" },
  { id: "ex30", name: "Calf Raise" },
];

export default PREDEFINED_EXERCISES;